Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// DIRECTION                0   xyzw        1     NONE   float   xyz 
// DIMENSIONS               0   xyz         2     NONE   float   xy  
// ALIGNBLENDBRIGHT         0   xyzw        3     NONE   float   x   
// AXIS                     0   xyzw        4     NONE   float   xyzw
// VERTEXALPHA              0   xy          5     NONE   float   xy  
// LIGHTINGATLASINDEX       0   xyzw        6     NONE     int   xyzw
// UVSCURRENTDIFFUSE        0   xyzw        7     NONE   float   xyzw
// UVSNEXTDIFFUSE           0   xyzw        8     NONE   float   xyzw
// TEXBLENDDIFFUSE          0   x           9     NONE   float   x   
// ATLASINDICESDIFFUSE      0   x          10     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 3   xyzw        0     NONE   float   xyzw
// TEXCOORD                 5   xyzw        1     NONE   float   xyzw
// TEXCOORD                 6   xyzw        2     NONE   float   xyzw
// TEXCOORD                10   xyzw        3     NONE   float   xyzw
// TEXCOORD                14   xyzw        4     NONE   float   xyzw
// TEXCOORD                15   xyzw        5     NONE   float   xyzw
// TEXCOORD                18   xy          6     NONE   float   xy  
// TEXCOORD                21   xyz         7     NONE   float   xyz 
// SV_POSITION              0   xyzw        8      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[12], immediateIndexed
dcl_constantbuffer CB1[280], immediateIndexed
dcl_constantbuffer CB2[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_input v3.x
dcl_input v4.xyzw
dcl_input v5.xy
dcl_input v6.xyzw
dcl_input v7.xyzw
dcl_input v8.xyzw
dcl_input v9.x
dcl_input v10.x
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xyzw
dcl_output o4.xyzw
dcl_output o5.xyzw
dcl_output o6.xy
dcl_output o7.xyz
dcl_output_siv o8.xyzw, position
dcl_temps 11
mul r0.xyz, v0.xyzx, cb1[222].zzzz
mul r1.xy, v2.xyxx, cb1[222].zzzz
max r1.z, |r1.y|, |r1.x|
and r1.w, v10.x, l(0x0000ffff)
ushr r2.x, v10.x, l(16)
utof o1.w, r1.w
utof o2.w, r2.x
mad o3.xy, v5.xyxx, v7.ywyy, v7.xzxx
mov r0.w, l(1.000000)
dp4 r2.x, cb0[9].xyzw, r0.xyzw
dp4 r2.y, cb0[10].xyzw, r0.xyzw
dp4 r2.z, cb0[11].xyzw, r0.xyzw
mul r0.xyz, cb1[278].zxyz, cb1[279].yzxy
mad r0.xyz, cb1[278].yzxy, cb1[279].zxyz, -r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
ne r0.w, r0.w, l(0.000000)
mov r3.x, cb1[279].y
mov r3.yz, l(0,0,0,0)
movc r0.xyz, r0.wwww, r0.xyzx, r3.xyzx
mul r3.xyz, r0.yzxy, cb1[279].zxyz
mad r3.xyz, cb1[279].yzxy, r0.zxyz, -r3.xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, r3.xyzx
dp3 r0.w, cb1[279].xyzx, r2.xyzx
mul r1.w, cb2[2].w, cb2[3].x
mad r2.w, -cb2[2].w, cb2[3].x, cb2[2].w
add r3.w, -r0.w, cb2[2].w
div_sat r1.w, r3.w, r1.w
add r1.w, -r1.w, l(1.000000)
lt r0.w, r2.w, r0.w
and r0.w, r0.w, l(0x3f800000)
mul r0.w, r0.w, r1.w
mul r1.w, v0.w, l(0.500000)
mad r2.w, v3.x, l(255.000000), l(0.500000)
ftou r2.w, r2.w
if_z r2.w
  mov r4.xyz, cb1[279].xyzx
else 
  mad r5.xyz, v1.xyzx, l(2.007874, 2.007874, 2.007874, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  dp3 r6.x, cb0[9].xyzx, r5.xyzx
  dp3 r6.y, cb0[10].xyzx, r5.xyzx
  dp3 r6.z, cb0[11].xyzx, r5.xyzx
  dp3 r3.w, r6.xyzx, r6.xyzx
  rsq r3.w, r3.w
  mul r5.xyz, r3.wwww, r6.xyzx
  ieq r6.xy, r2.wwww, l(1, 2, 0, 0)
  or r3.w, r6.y, r6.x
  if_nz r3.w
    mul r6.xyz, r2.zxyz, r5.yzxy
    mad r6.xyz, r2.yzxy, r5.zxyz, -r6.xyzx
    dp3 r3.w, r6.xyzx, r6.xyzx
    rsq r3.w, r3.w
    mul r0.xyz, r3.wwww, r6.xyzx
    mul r6.xyz, r0.zxyz, cb1[279].yzxy
    mad r4.xyz, r0.yzxy, cb1[279].zxyz, -r6.xyzx
    mov r3.xyz, r5.xyzx
    mov r1.w, l(0)
  else 
    mad r6.xyz, v4.xyzx, l(2.007874, 2.007874, 2.007874, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    dp3 r7.x, cb0[9].xyzx, r6.xyzx
    dp3 r7.y, cb0[10].xyzx, r6.xyzx
    dp3 r7.z, cb0[11].xyzx, r6.xyzx
    dp3 r3.w, r7.xyzx, r7.xyzx
    rsq r3.w, r3.w
    mul r4.xyz, r3.wwww, r7.xyzx
    ieq r2.w, r2.w, l(4)
    if_z r2.w
      mul r6.xyz, r5.yzxy, r4.zxyz
      mad r5.xyz, r4.yzxy, r5.zxyz, -r6.xyzx
      dp3 r2.w, r5.xyzx, r5.xyzx
      rsq r2.w, r2.w
      mul r0.xyz, r2.wwww, r5.xyzx
      mul r5.xyz, r4.yzxy, r0.zxyz
      mad r3.xyz, r0.yzxy, r4.zxyz, -r5.xyzx
    endif 
  endif 
endif 
add r1.w, r1.w, r1.w
sincos r5.x, r6.x, r1.w
dp3 r1.w, r4.xyzx, r4.xyzx
rsq r1.w, r1.w
mul r5.yzw, r1.wwww, r4.xxyz
add r2.w, -r6.x, l(1.000000)
mul r7.xyzw, r5.yyyz, r2.wwww
mul r6.yzw, r5.wwyz, r5.xxxx
mad r8.xy, r7.zyzz, r5.wzww, r6.wyww
mad r9.xy, r7.xwxx, r5.yzyy, r6.xxxx
mad r8.z, r7.w, r5.w, -r6.z
mad r10.xy, r7.yzyy, r5.zwzz, -r6.ywyy
mad r10.z, r7.w, r5.w, r6.z
mul r3.w, r5.w, r5.w
mad r10.w, r3.w, r2.w, r6.x
mov r9.z, r10.x
mov r9.w, r8.x
dp3 r5.x, r9.xzwx, r0.xyzx
mov r8.w, r9.y
dp3 r5.y, r8.ywzy, r0.xyzx
dp3 r5.z, r10.yzwy, r0.xyzx
dp3 r0.x, r5.xyzx, r5.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, r5.xyzx
dp3 r5.x, r9.xzwx, r3.xyzx
dp3 r5.y, r8.ywzy, r3.xyzx
dp3 r5.z, r10.yzwy, r3.xyzx
dp3 r2.w, r5.xyzx, r5.xyzx
rsq r2.w, r2.w
mul r3.xyz, r2.wwww, r5.xyzx
mad r5.xyz, r0.xyzx, r1.xxxx, r2.xyzx
mad r5.xyz, r3.xyzx, r1.yyyy, r5.xyzx
lt r0.w, r0.w, l(0.001000)
movc r0.w, r0.w, l(0), l(1.000000)
add r5.xyz, -r2.xyzx, r5.xyzx
mad r2.xyz, r5.xyzx, r0.wwww, r2.xyzx
lt r5.xy, l(0.000000, 0.000000, 0.000000, 0.000000), r1.xyxx
lt r5.zw, r1.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
iadd r5.xy, -r5.xyxx, r5.zwzz
itof r5.xy, r5.xyxx
mul r5.yzw, r3.xxyz, r5.yyyy
mad r5.xyz, r0.xyzx, r5.xxxx, r5.yzwy
mad r4.xyz, -r4.xyzx, r1.wwww, r5.xyzx
dp3 r0.w, r4.xyzx, r4.xyzx
rsq r0.w, r0.w
mul o5.xyz, r0.wwww, r4.xyzx
mul r4.xyz, r2.yyyy, cb1[230].xyzx
mad r4.xyz, r2.xxxx, cb1[229].xyzx, r4.xyzx
mad r4.xyz, r2.zzzz, cb1[231].xyzx, r4.xyzx
add o7.xyz, r4.xyzx, cb1[232].xyzx
mul r4.xyz, r2.yyyy, cb1[271].xywx
mad r4.xyz, r2.xxxx, cb1[270].xywx, r4.xyzx
mad r4.xyz, r2.zzzz, cb1[272].xywx, r4.xyzx
add o0.xyz, r4.xyzx, cb1[273].xywx
ige r0.w, v6.x, l(0)
if_nz r0.w
  div r4.xy, r1.xyxx, r1.zzzz
  add r4.xy, r4.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
  mul r4.xy, r4.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
  itof r5.xyzw, v6.wzxy
  mul r6.xyz, r5.xxyx, cb1[222].xyyx
  mul r4.x, r4.x, r6.x
  mad r4.z, r4.y, r6.y, r6.z
  mad r4.xy, r6.xyxx, r5.zwzz, r4.xzxx
  add r4.z, r4.y, l(-1.000000)
  add r4.xy, r4.xzxx, l(-0.500000, 0.500000, 0.000000, 0.000000)
  add r4.xy, r4.xyxx, r4.xyxx
  mov r4.z, l(0)
else 
  mov r4.xyz, l(1000.000000,10000.000000,-10.000000,0)
endif 
mad o3.zw, v5.xxxy, v8.yyyw, v8.xxxz
mov o0.w, v4.w
mov o1.xyz, r0.xyzx
mov o2.xyz, r3.xyzx
mov o4.w, v9.x
mov o4.xyz, r2.xyzx
mov o5.w, r1.z
mov o8.xyz, r4.xyzx
mov o8.w, l(1.000000)
mov o6.xy, r1.xyxx
ret 
// Approximately 0 instruction slots used
