Microsoft (R) Direct3D Shader Compiler 10.1
Copyright (C) 2013 Microsoft. All rights reserved.

//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// DIRECTION                0   xyzw        1     NONE   float   xyz 
// DIMENSIONS               0   xyz         2     NONE   float   xy  
// ALIGNBLENDBRIGHT         0   xyzw        3     NONE   float   x   
// BRIGHTNESS               0   x           4     NONE   float   x   
// AXIS                     0   xyzw        5     NONE   float   xyz 
// VERTEXALPHA              0   xy          6     NONE   float   xy  
// UVSCURRENTDIFFUSE        0   xyzw        7     NONE   float   xyzw
// ATLASINDICESDIFFUSE      0   x           8     NONE   float   x   
// COLOUR                   0   xyzw        9     NONE   float      w
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 3   xyz         0     NONE   float   xyz 
// TEXCOORD                 5   xyzw        1     NONE   float   xyzw
// SV_POSITION              0   xyzw        2      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[12], immediateIndexed
dcl_constantbuffer CB1[280], immediateIndexed
dcl_constantbuffer CB2[3], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_input v3.x
dcl_input v4.x
dcl_input v5.xyz
dcl_input v6.xy
dcl_input v7.xyzw
dcl_input v8.x
dcl_input v9.w
dcl_output o0.xyz
dcl_output o1.xyzw
dcl_output_siv o2.xyzw, position
dcl_temps 8
mul r0.xyz, v0.xyzx, cb1[222].zzzz
mul r1.xy, v2.xyxx, cb1[222].zzzz
and r1.z, v8.x, l(0x0000ffff)
utof o0.y, r1.z
mad o1.xy, v6.xyxx, v7.ywyy, v7.xzxx
mov r0.w, l(1.000000)
dp4 r2.x, cb0[9].xyzw, r0.xyzw
dp4 r2.y, cb0[10].xyzw, r0.xyzw
dp4 r2.z, cb0[11].xyzw, r0.xyzw
mul r0.xyz, cb1[278].zxyz, cb1[279].yzxy
mad r0.xyz, cb1[278].yzxy, cb1[279].zxyz, -r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
rsq r0.w, r0.w
mul r0.xyz, r0.wwww, r0.xyzx
dp3 r0.w, r0.xyzx, r0.xyzx
ne r0.w, r0.w, l(0.000000)
mov r3.x, cb1[279].y
mov r3.yz, l(0,0,0,0)
movc r0.xyz, r0.wwww, r0.xyzx, r3.xyzx
mul r3.xyz, r0.yzxy, cb1[279].zxyz
mad r3.xyz, cb1[279].yzxy, r0.zxyz, -r3.xyzx
dp3 r0.w, r3.xyzx, r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, r3.xyzx
dp3 r0.w, cb1[279].xyzx, r2.xyzx
mul r1.z, cb2[1].w, cb2[2].x
mad r1.w, -cb2[1].w, cb2[2].x, cb2[1].w
add r2.w, -r0.w, cb2[1].w
div_sat r1.z, r2.w, r1.z
add r1.z, -r1.z, l(1.000000)
lt r0.w, r1.w, r0.w
and r0.w, r0.w, l(0x3f800000)
mul r0.w, r0.w, r1.z
mul r1.z, v0.w, l(0.500000)
lt r1.w, v3.x, l(0.001961)
if_nz r1.w
  mov r4.xyz, cb1[279].xyzx
else 
  mad r5.xyz, v1.xyzx, l(2.007874, 2.007874, 2.007874, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
  dp3 r6.x, cb0[9].xyzx, r5.xyzx
  dp3 r6.y, cb0[10].xyzx, r5.xyzx
  dp3 r6.z, cb0[11].xyzx, r5.xyzx
  dp3 r1.w, r6.xyzx, r6.xyzx
  rsq r1.w, r1.w
  mul r5.xyz, r1.wwww, r6.xyzx
  lt r1.w, v3.x, l(0.005882)
  if_nz r1.w
    mul r6.xyz, r2.zxyz, r5.yzxy
    mad r6.xyz, r2.yzxy, r5.zxyz, -r6.xyzx
    dp3 r1.w, r6.xyzx, r6.xyzx
    rsq r1.w, r1.w
    mul r0.xyz, r1.wwww, r6.xyzx
    mul r6.xyz, r0.zxyz, cb1[279].yzxy
    mad r4.xyz, r0.yzxy, cb1[279].zxyz, -r6.xyzx
    mov r3.xyz, r5.xyzx
    mov r1.z, l(0)
  else 
    lt r1.w, v3.x, l(0.009804)
    if_nz r1.w
      mul r6.xyz, r2.zxyz, r5.yzxy
      mad r6.xyz, r2.yzxy, r5.zxyz, -r6.xyzx
      dp3 r1.w, r6.xyzx, r6.xyzx
      rsq r1.w, r1.w
      mul r0.xyz, r1.wwww, r6.xyzx
      mul r6.xyz, r0.zxyz, cb1[279].yzxy
      mad r4.xyz, r0.yzxy, cb1[279].zxyz, -r6.xyzx
      mov r3.xyz, r5.xyzx
      mov r1.z, l(0)
    else 
      mad r6.xyz, v5.xyzx, l(2.007874, 2.007874, 2.007874, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
      dp3 r7.x, cb0[9].xyzx, r6.xyzx
      dp3 r7.y, cb0[10].xyzx, r6.xyzx
      dp3 r7.z, cb0[11].xyzx, r6.xyzx
      dp3 r1.w, r7.xyzx, r7.xyzx
      rsq r1.w, r1.w
      mul r4.xyz, r1.wwww, r7.xyzx
      lt r1.w, v3.x, l(0.013725)
      if_nz r1.w
        mul r6.xyz, r5.yzxy, r4.zxyz
        mad r0.xyz, r4.yzxy, r5.zxyz, -r6.xyzx
        mul r6.xyz, r4.yzxy, r0.zxyz
        mad r3.xyz, r0.yzxy, r4.zxyz, -r6.xyzx
      else 
        lt r1.w, v3.x, l(0.017647)
        if_z r1.w
          mul r6.xyz, r5.yzxy, r4.zxyz
          mad r0.xyz, r4.yzxy, r5.zxyz, -r6.xyzx
          mul r5.xyz, r4.yzxy, r0.zxyz
          mad r3.xyz, r0.yzxy, r4.zxyz, -r5.xyzx
        endif 
      endif 
    endif 
  endif 
endif 
sincos r5.x, r6.x, r1.z
mul r4.xyz, r4.xyzx, r5.xxxx
mov r4.w, r6.x
add r5.xyzw, r4.xyzw, r4.xyzw
mul r6.yzw, r0.yyzx, r4.zzxy
mad r6.yzw, r4.yyzx, r0.zzxy, -r6.yyzw
dp3 r1.z, r4.xyzx, r0.xyzx
mul r1.w, r6.x, r5.w
mad r0.xyz, r1.wwww, r0.xyzx, -r0.xyzx
mad r0.xyz, r1.zzzz, r5.xyzx, r0.xyzx
mad r0.xyz, r6.yzwy, r5.wwww, r0.xyzx
mul r6.xyz, r3.yzxy, r4.zxyz
mad r6.xyz, r4.yzxy, r3.zxyz, -r6.xyzx
dp3 r1.z, r4.xyzx, r3.xyzx
mad r3.xyz, r1.wwww, r3.xyzx, -r3.xyzx
mad r3.xyz, r1.zzzz, r5.xyzx, r3.xyzx
mad r3.xyz, r6.xyzx, r5.wwww, r3.xyzx
mad r0.xyz, r0.xyzx, r1.xxxx, r2.xyzx
mad r0.xyz, r3.xyzx, r1.yyyy, r0.xyzx
lt r1.z, r0.w, l(0.001000)
movc r1.z, r1.z, l(0), l(1.000000)
add r0.xyz, -r2.xyzx, r0.xyzx
mad r0.xyz, r0.xyzx, r1.zzzz, r2.xyzx
mul r2.xyzw, r0.yyyy, cb1[271].xyzw
mad r2.xyzw, r0.xxxx, cb1[270].xyzw, r2.xyzw
mad r2.xyzw, r0.zzzz, cb1[272].xyzw, r2.xyzw
add r2.xyzw, r2.xyzw, cb1[273].xyzw
eq r0.x, cb2[0].y, l(0.000000)
if_nz r0.x
  max r0.x, r2.w, l(0.000000)
  rsq r0.x, r0.x
else 
  max r0.y, |r1.y|, |r1.x|
  max r0.z, r2.w, l(0.000000)
  mul r0.yz, r0.yyzy, r0.yyzy
  mul r1.x, r0.y, cb2[0].y
  mad r0.y, r0.z, l(1.944738), r0.y
  div r0.x, r1.x, r0.y
endif 
mul o0.z, r0.w, r0.x
mul o1.z, r0.w, v9.w
mov o1.w, v4.x
mov o2.xyzw, r2.xyzw
mov o0.x, r2.w
ret 
// Approximately 0 instruction slots used
