#pragma once

// The temporal reprojection shader. Its arithmetic mirrors
// src/common/temporal_math.h. Compiled by temporal_shader_build during the
// build; the graphics DLL consumes only its generated bytecode.
//
// Two things happen in gamma space on purpose. The blend: bright hairlines
// in linear light would dominate their neighbours' average, and a
// perceptual space is where every shipped TAA does its accumulation. And
// the history: stored as the output is, so a frame with no history to
// blend is bit-for-bit the game's own.
namespace edvr {

constexpr char kTemporalCsHlsl[] = R"HLSL(
#ifndef EDVR_TEMPORAL_DIAGNOSTICS
#define EDVR_TEMPORAL_DIAGNOSTICS 1
#endif
#ifndef EDVR_TEMPORAL_TRACE
#define EDVR_TEMPORAL_TRACE 0
#endif
Texture2D<float4> S : register(t0);      // this frame, the game's own texture (or the region copied out of it)
Texture2D<float4> H : register(t1);      // the history, region-sized, on the unjittered grid
Texture2D<float> Z : register(t2);       // the scene's depth, the game's own, when the pass has it
SamplerState L : register(s0);           // bilinear, clamp
RWTexture2D<float4> O : register(u0);    // the output: region-sized in the game's format for main, and for mv's debug views the trained runtime's OUTPUT texture, which is LARGER under DLSS -- paintDebug, not O[id.xy]
RWTexture2D<float4> N : register(u1);    // the new history
RWStructuredBuffer<uint> Stats : register(u2);   // 0 rejected, 1 clipped, 2 the clips' size (luma/255, summed); then the same three per candidate, four of them; 15 pixels on the world path, 16 bright pixels, 17 bright pixels with no depth; 18-20 the registration probes on the world path (sum dx*100, sum dy*100, count) and 21-23 on the ship; 24-27 world pixels, world clipped, ship pixels, ship clipped; 28 the mover mask's pixels; 29 unused (the body path's, retired 2026-09-23); 30-32 the registration probes on the sky (the far plane: sum dx*100, sum dy*100, count); 33-34 the probes' sum resid.mv*100 and sum mv.mv*100 on the sky, 35-36 on the world with a depth, 37-38 on the ship; 39-49 unused (the estimated ship, second-body and stepped-part paths' counters, retired 2026-09-23); 50-54 the engine path's pixel kinds (mv only, gCount 48-52)
RWTexture2D<float2> MV : register(u3);   // for a trained pass: motion vectors, pixels, current -> previous
RWTexture2D<float>  ZC : register(u4);   // and the depth, copied as it is (both entries, when the mover mask wants last frame's)
Texture2D<float> ZP : register(t3);      // last frame's ZC; movers.x or holoJitter.w validates it
Texture2D<float> UM : register(t4);      // the interface's reactive mask (ui_depth.h), folded into MK when probe.z says it is bound
Texture2D<float> ZS : register(t6);      // the drives' smoke's own depth (ui_depth.h, uiDepthSmokeDepth), the scene depth's size; unbound = none this frame, and reads as the far value
Texture2D<float> ZUI : register(t7);     // private UI depth; never used by game draws
Texture2D<float4> UP : register(t8);     // previous raw-raster UI colour; alpha is coverage, not opacity
Texture2D<uint> TI : register(t9);      // terrain patch index, zero outside rasterised coverage
Texture2D<float> TZ : register(t10);    // terrain depth, compared against final scene/UI depth
struct TerrainRecord { uint4 key[12]; float4 q; float4 t; float4 r[3]; };
Texture2D<float2> HC : register(t12);
struct HoloRecord { uint4 key[8]; float4 clip[3]; float4 map[3]; float4 meta; };
StructuredBuffer<HoloRecord> HR : register(t13);
)HLSL"
R"HLSL(
// ENGINE_MOTION_HLSL_BEGIN
// Engine-record motion (with fix.temporal_aa, phase 1; docs/kinematic-motion-
// injection-2026-09-19.md, 2026-09-23 "Phase 1 built"). This block is the one
// text both the compose and tools/engine_velocity_test compile: the rig cuts
// it out between the two marker lines, so keep it self-contained.
// Bound only while probe.w bit 2048 says all four are: ES t21 is MRT6 of the
// game's own substituted pool draws (x = the t33 slot the draw read, -1 =
// none; y = the depth the fragment wrote), EP t22 the pool exactly as this
// eye's draws read it (the previous pose block and marker EDVR wrote at the
// engine's emit), EN b1 / EB b2 the game's scene constants this frame and last.
//
// EnginePoolRecord is the t33 record (the 0x150-byte batch item):
//   data[0]  = base u32 (bytes 0-3), scale f32 (4-7), packed quaternion (8-15)
//   data[1]  = position f32x3 (16-27), word28
//   data[18] = marker (288) + the PREVIOUS position EDVR wrote (292-303)
//   data[19] = base (304), scale (308), the PREVIOUS packed quaternion (312-319)
// The marker is self-checking: byte 288 is uninitialised in every producer
// (no store in any of them), so a constant would false-match stack garbage.
// It is the tag XOR a hash of the record's own two pose blocks, the same
// hash engine_velocity_emit.h writes. The pose decode and turn() are the
// pool vertex shaders' own (1/32767, not 2/65535).
//
// The CORE between the two inner markers declares no resource: the on-foot
// screen shader (screen_motion.h, kScreenMotionPs) is compiled with this same
// text in front of it -- tools/temporal_shader_build emits it as
// kEngineMotionCoreHlsl -- and carries source pixels by the same arithmetic.
// ENGINE_MOTION_CORE_BEGIN
struct EnginePoolRecord { uint4 data[21]; };
float4 engineQuat(uint2 packed) {
    return float4(packed.x & 65535u, packed.x >> 16, packed.y & 65535u, packed.y >> 16) * (1.0 / 32767.0) - 1.0;
}
float3 engineTurn(float4 q, float3 v) {
    return (2.0 * q.w * q.w - 1.0) * v + 2.0 * dot(q.xyz, v) * q.xyz + 2.0 * q.w * cross(q.xyz, v);
}
uint engineMarkerHash(EnginePoolRecord r) {
    uint words[10] = {r.data[1].x, r.data[1].y, r.data[1].z, r.data[0].z, r.data[0].w,
                      r.data[18].y, r.data[18].z, r.data[18].w, r.data[19].z, r.data[19].w};
    uint h = 0x811C9DC5u;
    [unroll] for (uint i = 0; i < 10; ++i) { h = (h ^ words[i]) * 0x01000193u; h ^= h >> 13; }
    return h;
}
// 1 joined (EDVR wrote the record's previous pose), 2 masked (a rig record
// EDVR could not follow), 3 neither (not a rig record: the camera term).
uint engineRecordKind(EnginePoolRecord r) {
    const uint h = engineMarkerHash(r);
    if (r.data[18].x == (0x7FC0ED01u ^ h)) return 1u;
    if (r.data[18].x == (0x7FC0ED02u ^ h)) return 2u;
    return 3u;
}
// Did the record's pose change between the two blocks (scale, quaternion,
// position, bit for bit)?
bool engineRecordMoved(EnginePoolRecord r) {
    return !(all(r.data[0].yzw == uint3(r.data[19].y, r.data[19].zw)) && all(r.data[1].xyz == r.data[18].yzw));
}
// The surface point under ndc at raw depth zr, carried by the record's own
// engine motion (current pose -> the previous pose EDVR wrote) and projected
// by last frame's clip rows. n0..n3 and nCam are this frame's rows 270..273
// and 275 of the scene constants the pool draw read, b0..b3 and bCam last
// frame's. False when either frame's rows are not the pool families'
// encoding (constant clip z, zero z column) or are degenerate.
bool engineReprojectRows(EnginePoolRecord r, float2 ndc, float zr,
                         float4 n0, float4 n1, float4 n2, float4 n3, float3 nCam,
                         float4 b0, float4 b1, float4 b2, float4 b3, float3 bCam, out float4 before) {
    before = 0;
    if (n0.z != 0.0 || n1.z != 0.0 || n2.z != 0.0 || n3.w != 0.0 || !(n3.z > 0.0) ||
        b0.z != 0.0 || b1.z != 0.0 || b2.z != 0.0 || b3.w != 0.0 || !(zr > 0.0))
        return false;
    // This frame: clip.xyw = world.x*n0 + world.y*n1 + world.z*n2 + n3 with
    // clip.w = the view depth = n3.z / zr. Solve the x, y, w rows.
    const float z = n3.z / zr;
    const float3 a = float3(n0.x, n1.x, n2.x);
    const float3 b = float3(n0.y, n1.y, n2.y);
    const float3 c = float3(n0.w, n1.w, n2.w);
    const float3 ca = cross(b, c), cb = cross(c, a), cc = cross(a, b);
    const float det = dot(a, ca);
    if (!(abs(det) > 1e-12) || !isfinite(det)) return false;
    const float3 rhs = float3(ndc * z - n3.xy, z);
    const float3 world = (ca * rhs.x + cb * rhs.y + cc * rhs.z) / det;   // less nCam
    float3 prevWorld;                                                    // less bCam
    if (!engineRecordMoved(r)) {
        prevWorld = world + (nCam - bCam);                               // did not move: the camera term
    } else {
        const float scaleNow = asfloat(r.data[0].y), scalePrev = asfloat(r.data[19].y);
        const float4 qNow = engineQuat(r.data[0].zw), qPrev = engineQuat(r.data[19].zw);
        const float3 mx = engineTurn(qNow, float3(scaleNow, 0, 0));
        const float3 my = engineTurn(qNow, float3(0, scaleNow, 0));
        const float3 mz = engineTurn(qNow, float3(0, 0, scaleNow));
        const float3 ix = cross(my, mz), iy = cross(mz, mx), iz = cross(mx, my);
        const float mdet = dot(mx, ix);
        if (!(abs(mdet) > 1e-30) || !isfinite(mdet)) return false;
        const float3 local = world - (asfloat(r.data[1].xyz) - nCam);   // scale * turn(qNow, v), as the VS formed it
        const float3 v = float3(dot(ix, local), dot(iy, local), dot(iz, local)) / mdet;
        prevWorld = (asfloat(r.data[18].yzw) - bCam) + scalePrev * engineTurn(qPrev, v);
    }
    before = prevWorld.x * b0 + prevWorld.y * b1 + prevWorld.z * b2 + b3;
    return before.w > 0.0 && all(isfinite(before));
}
// ENGINE_MOTION_CORE_END
Texture2D<float2> ES : register(t21);
StructuredBuffer<EnginePoolRecord> EP : register(t22);
cbuffer EngineNow : register(b1) { float4 EN[276]; };
cbuffer EngineBefore : register(b2) { float4 EB[276]; };
// The eye path: this eye's own scene constants, this frame's and last.
bool engineReproject(EnginePoolRecord r, float2 ndc, float zr, out float4 before) {
    return engineReprojectRows(r, ndc, zr, EN[270], EN[271], EN[272], EN[273], EN[275].xyz,
                               EB[270], EB[271], EB[272], EB[273], EB[275].xyz, before);
}
// ENGINE_MOTION_HLSL_END
)HLSL"
R"HLSL(
Texture2D<float4> Screen : register(t14);
StructuredBuffer<TerrainRecord> TR : register(t11);
RWTexture2D<float4> UN : register(u6);   // this frame's UI evidence, separate from accumulated colour
RWTexture2D<float> MK : register(u5);    // for a trained pass: the mover mask, NVIDIA's bias-current-colour input (ONE texture: the interface's mask is folded in)
#if EDVR_TEMPORAL_TRACE
RWTexture2D<float4> DT : register(u7);   // capture-only final path decision: physical motion xy, predicted previous depth z, integer flags w
#else
RWTexture2D<float2> ML : register(u7);   // the fovea crop's own copy of MV, plus lead.xy (the head lead): bound ONLY on the fovea prep's dispatch, and read only by NVIDIA's crop
#endif
cbuffer P : register(b0) {
    int4   region;      // x0 y0 x1 y1: this eye's pixels in S (x1, y1 exclusive)
    int2   size;        // the region's size = the output's
    int2   texSize;     // S's size, for the sampler's uv
    float4 tanNow;      // l r t b this frame, jitter excluded
    float4 tanPrev;     // l r t b for the frame the history holds
    float4 jit;         // xy this frame's jitter in pixels; z 1 = filter the current sample; w the history kernel's C
    float4 dR0;         // rows of the rotation taking this frame's view
    float4 dR1;         // directions to last frame's (xyz; w unused)
    float4 dR2;
    float4 c0R0;        // the registration instrument's candidates, same
    float4 c0R1;        // shape: 0 the head's rotation alone, 1 the eyes swapped,
    float4 c0R2;        // 2 the world path's delta from the rows, 3 the
    float4 c1R0;        // head with depth as used
    float4 c1R1;
    float4 c1R2;
    float4 c2R0;
    float4 c2R1;
    float4 c2R2;
    float4 c3R0;
    float4 c3R1;
    float4 c3R2;
    float  blend;       // history weight
    float  gamma;       // clip half-width, in standard deviations
    int    haveHistory; // 0: nothing to blend, this frame goes out as it is
    int    candMask;    // bit c: candidate c has a delta this frame
    float4 knobs;       // x, z: the depth's encoding, written = x + z / metres (reversed-Z; x = 0 with no far plane); y 1 = depth bound; w the runtime's far, unused
    float4 tvUsed;      // xyz the translation term for the used delta (depth motion), w unused
    float4 tvCand;      // xyz the same for the instrument's swapped-eyes candidate
    float4 tvCam;       // xyz the translation term for the camera rows (the world path); w 1 = the world path is on
    float4 split;       // x the ship's radius in metres (nearer: the head's delta; farther and the far plane: the camera's); y the debug view (1 motion, 2 error, 3 depth); z a depth in metres for depthless pixels in a menu-like scene (0 off); w 1 = menu-like scene
    float4 fovea0;      // xy the fovea centre in output pixels, z the inner radius (px) where the periphery calming starts, w 1/(the ramp width in px)
    float4 fovea1;      // x the periphery calm strength (0..1), w 1 = the fovea is on (else no modulation)
    float4 movers;      // x 1 = the mover mask is on (ZP holds last frame's depth for this frustum); y the depth tolerance, a fraction; z the strength, how much history a masked pixel loses (0..1); w 1 = main writes ZC
    float4 probe;       // x history scale, y registration probes, z coverage bound; w bits: 1 fixed bias, 2 prior UI valid, 4 adaptive UI, 8 terrain, 16 holo, 32 screen, 128 the scanner's screen is up (its interface takes the head's path)
    float4 holoJitter; // current minus previous raster jitter; z = consecutive treated frames; w = valid DLSS depth history
    float4 skip;        // the fovea's own-resolve early-out: x0 y0 x1 y1 in THIS render, all zero = no skip
    float4 lead;        // xy: how far the fovea crop's base slid THIS frame (render pixels, base_now - base_prev), added to the vectors written to ML for NVIDIA's crop alone; zero on every other dispatch. zw unused
};
float3 rgbToYcocg(float3 c) {
    return float3(0.25 * c.r + 0.5 * c.g + 0.25 * c.b,
                  0.5 * c.r - 0.5 * c.b,
                  -0.25 * c.r + 0.5 * c.g - 0.25 * c.b);
}
float3 ycocgToRgb(float3 y) {
    return float3(y.x + y.y - y.z, y.x + y.z, y.x - y.y - y.z);
}
// Pull q into the box along the ray from the box's centre: the standard
// AABB clip, which keeps the history's hue while bounding its distance.
float3 clipToBox(float3 mn, float3 mx, float3 q) {
    float3 c = 0.5 * (mx + mn);
    float3 e = 0.5 * (mx - mn) + 1e-5;
    float3 v = q - c;
    float3 a = abs(v / e);
    float ma = max(a.x, max(a.y, a.z));
    return ma > 1.0 ? c + v / ma : q;
}
// The history's resampling kernel through nine bilinear fetches: a
// bicubic of the B = 0 family with C from the parameters -- C = 0.5 is
// Catmull-Rom, larger C is sharper with more ringing (0.75 is a common
// "sharp bicubic"). Every frame the history is fetched at a sub-pixel
// offset, since a tracked head is never quite still, and each fetch is a
// low-pass whose losses compound through the exponential average: at a
// third of a cycle per pixel Catmull-Rom keeps about half of the
// contrast after that compounding at a 0.9 blend, and a sharper kernel
// keeps more. advanced.temporal_aa_history_sharp sets C, live.
float4 catmullRom(float2 uv, float2 tsize) {
    float C = jit.w;
    float2 sp = uv * tsize;
    float2 t1 = floor(sp - 0.5) + 0.5;
    float2 f = sp - t1;
    float2 g0 = 1.0 + f;
    float2 g3 = 2.0 - f;
    float2 w0 = C * (-g0 * g0 * g0 + 5.0 * g0 * g0 - 8.0 * g0 + 4.0);
    float2 w1 = (2.0 - C) * f * f * f + (C - 3.0) * f * f + 1.0;
    float2 h = 1.0 - f;
    float2 w2 = (2.0 - C) * h * h * h + (C - 3.0) * h * h + 1.0;
    float2 w3 = C * (-g3 * g3 * g3 + 5.0 * g3 * g3 - 8.0 * g3 + 4.0);
    float2 w12 = w1 + w2;
    float2 o12 = w2 / w12;
    float2 t0 = (t1 - 1.0) / tsize;
    float2 t3 = (t1 + 2.0) / tsize;
    float2 t12 = (t1 + o12) / tsize;
    float4 r = 0.0;
    r += H.SampleLevel(L, float2(t0.x, t0.y), 0) * w0.x * w0.y;
    r += H.SampleLevel(L, float2(t12.x, t0.y), 0) * w12.x * w0.y;
    r += H.SampleLevel(L, float2(t3.x, t0.y), 0) * w3.x * w0.y;
    r += H.SampleLevel(L, float2(t0.x, t12.y), 0) * w0.x * w12.y;
    r += H.SampleLevel(L, float2(t12.x, t12.y), 0) * w12.x * w12.y;
    r += H.SampleLevel(L, float2(t3.x, t12.y), 0) * w3.x * w12.y;
    r += H.SampleLevel(L, float2(t0.x, t3.y), 0) * w0.x * w3.y;
    r += H.SampleLevel(L, float2(t12.x, t3.y), 0) * w12.x * w3.y;
    r += H.SampleLevel(L, float2(t3.x, t3.y), 0) * w3.x * w3.y;
    return r;
}
// temporalReproject, transcribed: the pixel's direction now, rotated into
// last frame's view by the rows given, projected through last frame's
// frustum, the history fetched there. False off the image or behind the
// eye. One function, so the instrument can ask it of every candidate.
// With a translation and depth, the pixel is a POINT, not a direction:
// P = z * d (d.z = -1, so z is the view depth in metres), moved to last
// frame's eye space by delta * P + tv, then projected. Without depth (the
// far plane, or none bound) the direction alone is rotated, which is the
// rotation-only path: exact at infinity, and what v1 was everywhere.
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
// Merge current scene depth with private smoke and UI coverage. The UI
// copy is seeded once per eye/frame; reading the latest scene here also
// lets later nearer geometry win. The game's live depth is never modified
// by these coverage passes. Reversed-Z; unbound layer SRVs read far (zero).
float zSceneAt(int2 q) {
    if((uint(probe.w+.5)&32u)!=0u) { float4 s=Screen.Load(int3(q,0));if(s.w>0)return s.z; }
    return max(max(Z.Load(int3(q, 0)), ZS.Load(int3(q, 0))), ZUI.Load(int3(q, 0)));
}
float zAt(int2 q) { return zSceneAt(q); }
// Tier 1 of docs/per-object-motion.md: the mover mask from depth
// consistency (2026-09-08). The reprojection says where this pixel's
// surface WAS if it moved with the camera alone -- at pp, at view depth
// zPred metres -- and last frame's depth copy says what actually was at
// pp. Where the two disagree the surface is either a mover (something the
// camera's vectors cannot follow: a station's rim, a ship crossing the
// view) or a disocclusion (the history at pp shows what was in front a
// frame ago), and both deserve less history: a moving edge stops trailing
// a ghost, and the far side of a pillar you move past stops showing the
// pillar. It compares against the RANGE of last frame's 3x3 around pp,
// not one texel: the jitter shifts the sample grid half a pixel between
// frames, and at a depth edge a single-texel compare fires on every
// silhouette every frame whether anything moved or not (the same reason
// the reprojection dilates). The far plane is consistent only with the
// far plane, so a pixel that is sky now where a hull was last frame -- a
// mover's trail -- is masked too. What it cannot see is a mover's
// INTERIOR at constant depth, which passes; that is the later tiers'
// work, and this is the floor under them. temporalMoverTest in
// temporal_math.h is the reference the test pins; this transcribes it.
// zPred <= 0 means the pixel has no depth now (the far plane, or none).
// `thick`: at least six of the nine texels around the pixel have a depth
// NOW. The "surface where only sky was" rule is for a hull's leading edge
// arriving over empty space; a THIN feature -- a text stroke the interface
// wrote depth under, a wire, a railing -- reprojects onto texels that had
// no depth last frame on every frame the head moves, and the rule called
// every one of them a mover (2026-09-08: the interface's text swam again
// with the mask on, the very thing ui_depth had fixed). A thin feature
// gets the range test alone.
float moverAt(float2 pp, float zPred, bool thick) {
    int2 pq = int2(round(pp));
    float zmin = 1e30;
    float zmax = 0.0;
    bool anyFar = false;
    [unroll] for (int oy = -1; oy <= 1; ++oy) {
        [unroll] for (int ox = -1; ox <= 1; ++ox) {
            int2 q = clamp(pq + int2(ox, oy), int2(0, 0), size - 1);
            float zr = ZP.Load(int3(q, 0));
            float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
            if (zr <= 0.0 || den <= 0.0) {
                anyFar = true;
            } else {
                float z = knobs.z / den;
                zmin = min(zmin, z);
                zmax = max(zmax, z);
            }
        }
    }
    if (zPred <= 0.0) return anyFar ? 0.0 : 1.0;   // sky now: consistent only with sky then
    if (zmax <= 0.0) return thick ? 1.0 : 0.0;     // a surface now where only sky was: a hull's edge, not a stroke's
    float tol = movers.y;
    return (zPred < zmin * (1.0 - tol) || zPred > zmax * (1.0 + tol)) ? 1.0 : 0.0;
}
// The interface's pixel, by ui_depth's coverage mask when it is bound
// (probe.z), as far as the surface paths are concerned. The mask's value is
// NVIDIA's reactive strength, and its QUANTUM'S PARITY is ui_depth's word
// on the path (floorBuffer there): even rides the surface's own path where
// the pixel sits on it -- a stroke drawn AT the surface, the docking
// hologram over the hub's drum -- and odd keeps the camera's path at the
// pixel's depth: the interface proper, the holo material's target markers,
// the target-time sprite, and a flight HUD stroke's core that floats over
// the scene at the scene's depth. The station's target brackets are the
// last kind: they track the station's centre and do not turn with it, and
// before 2026-09-09 (when a band of values said which, and every stroke
// fell in the riding band) they rode the station's spin where they
// crossed its silhouette and kept the camera's path over the sky beside
// it -- "shimmering on just one side". One exception to the odd kind: in
// the scanner (probe.w bit 128) the camera is not the head, and every
// interface pixel takes the head's path instead (fetchHistoryT says).
// UI history decisions compare UI evidence, independently of fixed bias.
// Flags in probe.w: 1 fixed bias, 2 previous evidence valid, 4 capture/adapt,
// 128 the scanner's screen is up.
// A one-pixel neighbourhood tolerates raster jitter and subpixel movement.
float4 uiEvidence(int2 q) {
    q = clamp(q, int2(0,0), size - 1);
    uint kind = uint(UM.Load(int3(q,0))*255.0+0.5) & 3u;
    float marked = probe.z != 0.0 && (kind == 1u || kind == 2u) ? 1.0 : 0.0;
    // Evidence lives on the raw raster grid, just like its coverage. Adding
    // jitter only to colour paired a glyph's mask with a neighbouring pixel.
    return marked != 0.0 ? float4(S.Load(int3(region.xy + q, 0)).rgb, 1.0) : 0.0;
}
float adaptiveUiReactive(int2 q, float2 previous) {
    uint flags = uint(probe.w + 0.5);
    if ((flags & 4u) == 0u) return 0.0;
    float4 current = uiEvidence(q);
    if ((flags & 2u) == 0u) return current.a;
    if (any(previous < 0) || any(previous > size-1)) return current.a;
    float4 old = UP.SampleLevel(L, (previous + .5) / float2(size), 0);
    if (current.a == 0.0 && old.a == 0.0) return 0.0;
    float3 lo = 1e10, hi = -1e10;
    float nowCount = 0.0;
    [unroll] for (int y=-1; y<=1; ++y) [unroll] for (int x=-1; x<=1; ++x) {
        float4 c = uiEvidence(q + int2(x,y));
        if (c.a != 0.0) { lo = min(lo,c.rgb); hi = max(hi,c.rgb); nowCount += 1.0; }
    }
    if (nowCount == 0.0 || old.a == 0.0) return 1.0;
    // Test the history actually reprojected here. Taking the best of nine
    // old colours let a black neighbour excuse stale white text on a dark
    // marked panel. Alpha is validity, so normalize the bilinear footprint
    // before comparing; unmarked background is not UI colour evidence.
    float3 e = max(max(lo-old.rgb/old.a,old.rgb/old.a-hi),0.0);
    float error = max(e.x,max(e.y,e.z));
    return saturate((error - 0.03) / 0.17);
}
bool uiCovered(int2 q) {
    if (probe.z == 0.0) return false;
    // UM is region-sized (this eye's own W x H, made from RTV0 at UI-draw
    // time); every caller here passes q in S's absolute space (region.xy +
    // local), so it must be undone here, the same as holoPixel's kind 5/2/4
    // branches do inline. Investigated 2026-09-25: region.xy is nonzero for
    // the second eye of Elite's double-wide Submit on every ordinary frame
    // (src/common/supersample_math.h), not just under a DLSS crop, so this
    // was reading UM out of its bounds (Load returns 0 out of range) and
    // uiCovered() reported "not covered" unconditionally on that eye.
    uint v = uint(UM.Load(int3(q - region.xy, 0)) * 255.0 + 0.5);
    return (v & 1u) != 0u;
}
// Follow the actual nearby panel transform, including pool quantization
// and animation. Coverage depth rejects later foreground geometry; orbital
// HC accepts its line in front of or equal to the physical scene depth.
// Offset is jitter for native TAA's output grid, zero for DLSS's input grid.
bool holoPixel(float2 p, float2 offset, out float2 pp, out float zp) {
    pp=0; zp=0;
    if((uint(probe.w+.5)&16u)==0u || holoJitter.z==0) return false;
    int2 q=region.xy+int2(round(p+offset));
    float2 cov=HC.Load(int3(q,0)); uint index=uint(cov.x+.5);
    if(index==0 || index>128) return false;
    if(cov.y<=knobs.x) return false;
    HoloRecord r=HR[index-1]; if(r.meta.w!=1) return false;
    if(r.key[3].w==2) {
        // Orbital coverage uses a read-only private DSV with the scene's
        // GEQUAL test. Its HC depth may therefore be in front of the
        // physical scene depth; only a nearer physical occluder rejects it.
        if(cov.y<zSceneAt(q)) return false;
    } else if(abs(zSceneAt(q)-cov.y)>abs(cov.y)*1e-6) return false;
    if(r.key[3].w==5) {
        uint kind=probe.z!=0 ? uint(UM.Load(int3(q-region.xy,0))*255.0+.5)&3u : 0u;
        if(kind!=3u) return false;
    } else if(r.key[3].w==2) {
        // Orbital line coverage is validated by its exact record/depth.  It
        // must not inherit a text mark produced by another UI draw, while
        // its own RT1 record remains eligible over the sky.
        uint kind=probe.z!=0 ? uint(UM.Load(int3(q-region.xy,0))*255.0+.5)&3u : 0u;
        if(kind==1u || kind==2u) return false;
    } else if(r.key[3].w==4) {
        // Planet coverage is scene-sized; UI marks are region-sized. Both
        // text kinds must keep their own motion over the distant surface.
        uint kind=probe.z!=0 ? uint(UM.Load(int3(q-region.xy,0))*255.0+.5)&3u : 0u;
        if(kind==1u || kind==2u) return false;
    } else if(r.key[3].w==1 ? uiCovered(q) : !uiCovered(q)) return false;
    float z=knobs.z/(cov.y-knobs.x);
    float2 ndc=(p+offset+region.xy+.5)/r.meta.yz*float2(2,-2)+float2(-1,1);
    if(r.key[3].w==3) {
        // Sprites intentionally draw over nearer geometry. Coverage stores
        // the selected scene depth for visibility validation, while motion
        // must use the sprite's actual plane (captured local Y=0), not that
        // foreground depth or the VS's forced Z=W.
        float3 normal=cross(r.clip[2].xyz,r.clip[0].xyz);
        float den=dot(normal,float3(ndc,1));
        if(den==0) return false;
        z=dot(normal,float3(r.clip[0].w,r.clip[1].w,r.clip[2].w))/den;
        if(z<=0 || !isfinite(z)) return false;
    }
    float4 current=float4(ndc*z,z,1);
    float3 before=float3(dot(r.map[0],current),dot(r.map[1],current),dot(r.map[2],current));
    if(before.z<=0 || !all(isfinite(before))) return false;
    pp=(before.xy/before.z*float2(.5,-.5)+.5)*r.meta.yz-.5-region.xy+holoJitter.xy-offset;
    zp=before.z;
    return all(isfinite(pp));
}
)HLSL"
R"HLSL(
// Engine-record motion (with fix.temporal_aa, phase 1; docs/kinematic-motion-
// injection-2026-09-19.md, 2026-09-23 "Phase 1 built"). The kinds:
//   0 no engine data at this pixel (unbound, unwritten, UI, screen);
//   1 JOINED: pp/zp hold the surface's exact previous position -- the point
//     under the pixel from this frame's clip rows, carried by the record's own
//     engine motion (its two pose blocks), projected by last frame's rows;
//   2 MASKED: a rig record EDVR could not follow -- no history, no vector;
//   3 a pool record that is not a rig record: the camera term stands;
//   4 STALE: the slot's depth is not the scene's (a later draw covers it);
//   5 CORRUPT: the depth is the scene's but the slot code is not an odd whole
//     number -- arithmetic (a blend, a sum) reached MRT6; declined, never
//     read as another record (the 2026-09-23 review, item 4).
// The arithmetic is the ENGINE_MOTION_HLSL block near the top (the rig cuts
// out and runs that same text). The ownership test is exact: the slot's
// recorded depth must be the scene depth bit for bit. The rows carry the
// raster jitter; holoJitter.xy takes the current-minus-previous difference out.
// haveZ (a literal at every call): the caller already holds the scene depth
// at exactly this texel -- the mv pass's offset-zero call passes sceneZraw,
// read from its depth tile at region.xy + id, which is q -- so it is not
// loaded again (the performance review's conditional shader change);
// jittered callers load it here.
uint enginePixelZ(float2 p, float2 offset, bool haveZ, float knownZ, out float2 pp, out float zp) {
    pp = 0; zp = 0;
    if ((uint(probe.w + 0.5) & 2048u) == 0u || holoJitter.z == 0) return 0u;
    const int2 q = region.xy + int2(round(p + offset));
    const float2 es = ES.Load(int3(q, 0));
    // The patched pool shaders write 2 * slot + 1: the cleared -1 and an
    // untouched texel both fall below 1.
    if (!(es.x >= 1.0)) return 0u;
    if (uiCovered(q)) return 0u;
    if ((uint(probe.w + 0.5) & 32u) != 0u && Screen.Load(int3(q, 0)).w > 0) return 0u;
    const float zr = haveZ ? knownZ : zSceneAt(q);
    if (!(zr > 0.0) || asuint(zr) != asuint(es.y)) return 4u;
    const uint code = uint(es.x);
    if (float(code) != es.x || (code & 1u) == 0u) return 5u;
    uint count, stride;
    EP.GetDimensions(count, stride);
    const uint slot = code >> 1u;
    if (slot >= count) return 0u;
    const EnginePoolRecord r = EP[slot];
    const uint kind = engineRecordKind(r);
    if (kind != 1u) return kind;
    uint w, h;
    ES.GetDimensions(w, h);
    const float2 dims = float2(w, h);
    const float2 ndc = (p + offset + region.xy + 0.5) / dims * float2(2, -2) + float2(-1, 1);
    float4 before;
    // A moving record whose motion cannot be computed here keeps no history
    // (masked); one that did not move keeps the camera term.
    if (!engineReproject(r, ndc, zr, before)) return engineRecordMoved(r) ? 2u : 0u;
    pp = (before.xy / before.w * float2(0.5, -0.5) + 0.5) * dims - 0.5 - region.xy + holoJitter.xy - offset;
    zp = before.w;
    if (all(isfinite(pp))) return 1u;
    return engineRecordMoved(r) ? 2u : 0u;
}
uint enginePixel(float2 p, float2 offset, out float2 pp, out float zp) {
    return enginePixelZ(p, offset, false, 0.0, pp, zp);
}
// The mv pass's tile of this frame's scene depth: the group's 8x8 with a
// two-texel apron, filled at the top of mv() and read by the pixel's own
// dilation and by backgroundHistoryHidden's footprint below.
groupshared float mvDepthTile[144];
// This frame's nearest depth about the pixel, over the previous footprint's
// image in this raster: the 3x3 widened by one texel per axis toward the
// side the rounding of pp moved it (e = round(pp) - pp, in [-0.5, 0.5]).
// The eye run of 2026-09-17 11:48 measured the directed 4x4 against the
// 5x5 on a still scene: 0.0003% against 0.0002% of the eye left marked,
// where the plain 3x3 left 0.35%, all of it the rounding.
float nearestDepthNow(int2 local,float2 e) {
    int x0=local.x+(e.x<0?0:1),y0=local.y+(e.y<0?0:1); // tile offsets: -2 or -1 from the pixel
    float nearest=0;
    [unroll]for(int y=0;y<4;++y) [unroll]for(int x=0;x<4;++x)
        nearest=max(nearest,mvDepthTile[(y0+y)*12+x0+x]-knobs.x);
    return nearest;
}
// A background vector can land on last frame's moving hull. Modern DLSS
// presets ignore the reactive mask and otherwise carry that bright edge
// into the sky on each roll. Reject this hidden history explicitly. The
// three-pixel footprint includes filtered colour at a silhouette; the
// relative depth margin keeps ordinary surface rounding out of the test.
bool backgroundHistoryHidden(int2 local,float2 p,float2 motion,float zraw,float zPred) {
    if(holoJitter.w==0 || holoJitter.z==0) return false;
    float2 pp=p+motion-holoJitter.xy; // ZP uses last frame's raw raster
    if(!all(isfinite(pp)) || any(pp<0) || any(pp>float2(size)-1)) return false;
    int2 q=int2(round(pp));
    float nearest=0;
    [unroll]for(int y=-1;y<=1;++y) [unroll]for(int x=-1;x<=1;++x)
        nearest=max(nearest,ZP.Load(int3(clamp(q+int2(x,y),int2(0,0),size-1),0))-knobs.x);
    // A nearer surface still beside the pixel NOW -- a rock beside the
    // terrain, a crater rim beside the sky, the camera still -- hid
    // nothing: the history's filtered colour at pp holds it exactly as
    // this frame's own footprint at p does. Only an occluder that has
    // left the neighbourhood hid this history (the hull the sky rolls
    // past). The camera path had this by construction, reprojecting the
    // 3x3-dilated depth; the terrain path's exact depth met the dilated
    // footprint at every terrain edge instead, 5.3% of the terrain's
    // pixels a frame walking with the jitter -- the shimmer of the eye
    // run of 2026-09-17 11:48 (docs/terrain-history-shimmer-2026-09-17.md).
    if(nearest<=nearestDepthNow(local,float2(q)-pp)*1.03) return false;
    // Use this pixel's depth validity, not the foreground depth used by
    // the camera fallback's 3x3 dilation beside the hull.
    if(zraw<=knobs.x) return nearest>0;
    return zPred>0 && nearest>knobs.z/zPred*1.03;
}
// Exact terrain coverage only. The patch transform is in DirectX view
// space (+Z forward); the pass's rays use the runtime's -Z convention.
bool terrainPixel(float2 p, float3 d, out float2 pp, out float zp) {
    pp=0; zp=0;
    if ((uint(probe.w+0.5)&8u)==0u) return false;
    int2 q=region.xy+int2(p);
    uint index=TI.Load(int3(q,0));
    if (knobs.y==0 || index==0 || index>512 || uiCovered(q)) return false;
    float zraw=TZ.Load(int3(q,0)), scene=zSceneAt(q);
    if (zraw<=knobs.x || abs(scene-zraw)>abs(zraw)*0.00001) return false;
    TerrainRecord rec=TR[index-1];
    if (rec.t.w!=1) return false;
    float z=knobs.z/(zraw-knobs.x);
    float4 here=float4(d.xy*z,z,1);
    float3 before=float3(dot(rec.r[0],here),dot(rec.r[1],here),dot(rec.r[2],here));
    if (before.z<=0 || !all(isfinite(before))) return false;
    zp=before.z;
    pp.x=(before.x/zp-tanPrev.x)/(tanPrev.y-tanPrev.x)*size.x-0.5;
    pp.y=(tanPrev.w-before.y/zp)/(tanPrev.w-tanPrev.z)*size.y-0.5;
    return true;
}
)HLSL"
R"HLSL(
// zPred: the predicted view depth of this pixel's surface in last frame's
// eye space, metres, for the mover mask -- 0 when the pixel took no real
// depth (the far plane, the menu's assumed depth, no depth bound).
// depthN: how many of the 3x3 around the pixel have a depth now, for the
// mask's thick-or-thin verdict (moverAt says); 0 when no depth was read.
bool fetchHistoryT(float2 p, float3 r0, float3 r1, float3 r2, float3 tv,
                   bool useDepth, bool allowWorld, out uint world, out float2 mvOut,
                   out float zPred, out uint depthN, out float3 hy) {
    float3 d;
    d.x = tanNow.x + (p.x + 0.5) / float(size.x) * (tanNow.y - tanNow.x);
    d.y = tanNow.w - (p.y + 0.5) / float(size.y) * (tanNow.w - tanNow.z);
    d.z = -1.0;
    float3 dp = float3(dot(r0, d), dot(r1, d), dot(r2, d));
    world = 0;
    mvOut = 0.0;
    zPred = 0.0;
    depthN = 0;
    hy=0;
    if(allowWorld && (uint(probe.w+.5)&32u)!=0u) {
        float4 s=Screen.Load(int3(region.xy+int2(round(p+jit.xy)),0));
        if(s.w>1)return false;
        if(s.w==1) {
            float2 previous=p+s.xy+holoJitter.xy;
            if(any(previous<0) || any(previous>float2(size)-1))return false;
            mvOut=previous-p;
            hy=rgbToYcocg(catmullRom((previous+.5)/float2(size),float2(size)).rgb);
            return true;
        }
    }
    // The world/ship split: the ship's own things (the cockpit, the hull)
    // move with the head's delta; everything farther than split.x metres,
    // and the far plane, moves with the game's CAMERA -- the head and the
    // ship together, the rows the instrument's candidate 2 reads -- which
    // is what a turning ship needs for its skybox and a station (the Pimax
    // flight of 2026-09-04 saw both smear; the review's F6). The split
    // needs a depth to classify by, so it runs only with one bound.
    bool worldOn = allowWorld && tvCam.w != 0.0 && split.x > 0.0 && knobs.y != 0.0;
    if (useDepth || worldOn) {
        // The NEAREST depth of the 3x3, not the pixel's own: at the edge of
        // a near thing against a far one the pixel's own depth is either,
        // and a history fetched by the far one at a text stroke's edge is
        // the "underwater" the second depth flight saw at rest. With the
        // nearest, the edge follows the thing in front, which is the
        // standard dilation every velocity-based filter does.
        float zr = 0.0;
        [unroll] for (int oy = -1; oy <= 1; ++oy) {
            [unroll] for (int ox = -1; ox <= 1; ++ox) {
                int2 q = clamp(int2(p) + int2(ox, oy), int2(0, 0), size - 1);
                float zs = zSceneAt(region.xy + q);
                zr = max(zr, zs);
                if (zs > 0.0) ++depthN;
            }
        }
        float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
        bool far = zr <= 0.0 || den <= 0.0;
        float z = far ? 0.0 : knobs.z / den;
        // The scanner's interface (probe.w bit 128: the FSS screen is up)
        // reads a scene depth past the split, and the rule for a stroke --
        // the camera's path at the pixel's depth -- assumes the camera is
        // the head, which in the scanner it is not: its camera pans while
        // the panel stays put in front of the seat (eye dump 170752,
        // docs/fss-scanner.md). Those pixels take the head's rows given,
        // at whatever depth they read.
        bool scannerUi = (uint(probe.w + 0.5) & 128u) != 0u && uiCovered(region.xy + int2(p));
        if (worldOn && (far || z > split.x) && !scannerUi) {
            world = 1;
            dp = float3(dot(c2R0.xyz, d), dot(c2R1.xyz, d), dot(c2R2.xyz, d));
            if (!far) {
                dp = dp * z + tvCam.xyz;
                zPred = -dp.z;
            }
        } else if (useDepth && !far) {
            dp = dp * z + tv;
            zPred = -dp.z;
        } else if (useDepth && far && split.w != 0.0 && split.z > 0.0) {
            // A menu-like scene's depthless pixels (the main menu's hangar
            // wall reads no depth and reprojected as the far plane, so it
            // detached under head translation): an assumed depth, the
            // player's choice, better than infinity for a wall a few metres
            // off. advanced.temporal_aa_menu_metres.
            dp = dp * split.z + tv;
        }
    }
    hy = 0.0;
    // Engine-record motion FIRST (with fix.temporal_aa, probe.w 2048): the
    // record's exact motion, or no history at all for a masked rig record.
    if (allowWorld) {
        float2 engineP; float engineZ;
        const uint engineKind = enginePixel(p, jit.xy, engineP, engineZ);
        if (engineKind == 2u) return false;
        if (engineKind == 1u) {
            if (any(engineP < 0) || any(engineP > float2(size) - 1)) return false;
            mvOut = engineP - p; zPred = engineZ; world = 0;
            hy = rgbToYcocg(catmullRom((engineP + .5) / float2(size), float2(size)).rgb);
            return true;
        }
    }
    if (dp.z >= -1e-6) return false;
    float xt = dp.x / -dp.z;
    float yt = dp.y / -dp.z;
    float2 pp;
    pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
    pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
    if (pp.x < 0.0 || pp.y < 0.0 || pp.x > float(size.x) - 1.0 ||
        pp.y > float(size.y) - 1.0) {
        return false;
    }
    // (A per-pixel "rest snap" once sat here, fetching the history at its
    // own texel under a fraction of a pixel of motion. Gone since
    // 2026-09-04: each frame re-registers by the frame's delta, not by the
    // accumulated error, so the motion it suppressed accumulated into a lag
    // of blend / (1 - blend) times that motion, about 0.7 px on slowly
    // drifting distant content, and differed across the image. The rest
    // lock, experimental.shimmer_rest, holds the pose at rest instead.)
    float2 terrainP; float terrainZ;
    if (allowWorld && terrainPixel(p,d,terrainP,terrainZ)) {
        pp=terrainP; zPred=terrainZ; world=1;
        if (any(pp<0) || any(pp>float2(size)-1)) return false;
    }
    float2 holoP; float holoZ;
    if (allowWorld && holoPixel(p,jit.xy,holoP,holoZ)) {
        pp=holoP; zPred=holoZ; world=0;
        if(any(pp<0) || any(pp>float2(size)-1)) return false;
    }
    mvOut = pp - p;
    hy = rgbToYcocg(catmullRom((pp + 0.5) / float2(size), float2(size)).rgb);
    return true;
}
// How far a clip moved the history, in luma, as a count of 1/255ths: a
// nudge on a text edge is a few, a history that landed somewhere else
// entirely is tens. Summed per reading, it separates the two where a
// count of clipped pixels cannot.
uint clipSize(float3 hc, float3 hy) {
    return uint(saturate(abs(hc.x - hy.x)) * 255.0 + 0.5);
}
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
#if EDVR_TEMPORAL_DIAGNOSTICS
// 0..47 are Stats' own slots; mv's 48..52 are engine-record motion's pixel
// counts (joined, masked, a pool record that is not a rig record, stale
// slot, corrupt slot code), flushed to Stats 50..54 (48/49 were the
// stepped-part path's, retired 2026-09-23).
groupshared uint gCount[53];
#endif
// A debug view's pixel, painted into the OUTPUT rather than at this
// thread's own index.
//
// The mv entry is dispatched over the RENDER size, because that is what it
// computes; its debug views are painted into O, which on this path is the
// trained runtime's OUTPUT texture. Those two are the same size under DLAA
// and are not under DLSS, and writing O[id.xy] put the whole frame in the
// top-left corner -- the view "skewed up and left" at 2x, and every debug
// view under DLSS wrong since the trained path was written (Sean,
// 2026-09-08). So each render pixel paints the block of output pixels that
// belongs to it: [ceil(id*s), ceil((id+1)*s)), which is exactly the set of
// output pixels that map back to this one, so the block tiles the output
// with no seam and no overlap. Four each way covers every ratio a trained
// runtime offers (ultra performance is three); at 1:1 it is one write, as
// before.
void paintDebug(uint2 idx, int2 sz, float3 c) {
    uint ow = 0, oh = 0;
    O.GetDimensions(ow, oh);
    if (ow == 0 || oh == 0 || sz.x <= 0 || sz.y <= 0) return;
    float2 s = float2(float(ow) / float(sz.x), float(oh) / float(sz.y));
    int2 lo = int2(ceil(float2(idx) * s));
    int2 hi = int2(ceil((float2(idx) + 1.0) * s));
    [unroll] for (int dy = 0; dy < 4; ++dy) {
        [unroll] for (int dx = 0; dx < 4; ++dx) {
            int2 q = lo + int2(dx, dy);
            if (q.x < hi.x && q.y < hi.y && q.x < int(ow) && q.y < int(oh)) {
                O[q] = float4(c, 1.0);
            }
        }
    }
}
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
// The motion vectors for a trained pass (DLAA): the same reprojection
// the history fetch does, written out instead of used -- the pixel's
// position last frame minus its position now, in render pixels, which
// is DLSS's convention with a scale of one (pinned on the desk by the
// conventions rig in tools/smoke, 2026-09-04). Off the image or behind
// the eye: no motion. The depth goes beside it, copied as the game wrote
// it (reversed-Z, told to the runtime as such). The world/ship split is
// the history fetch's, transcribed, and the counts feed the registration
// line the way main's do.
[numthreads(8, 8, 1)]
void mv(uint3 id : SV_DispatchThreadID, uint gi : SV_GroupIndex) {
    int2 local = int2(gi & 7u, gi >> 3u);
    int2 origin = int2(id.xy) - local;
    for (uint k = gi; k < 144; k += 64) {
        int2 q = clamp(origin + int2(k % 12, k / 12) - 2, int2(0,0), size - 1);
        mvDepthTile[k] = zSceneAt(region.xy + q);
    }
    GroupMemoryBarrierWithGroupSync();
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 53) gCount[gi] = 0;
    GroupMemoryBarrierWithGroupSync();
#endif
    // Three counters, not forty. This pass writes 15, 16 and 17 and no
    // others, and a forty-element local array costs forty registers of
    // occupancy on a dispatch that covers the whole eye.
    uint count15 = 0, count16 = 0, count17 = 0, count28 = 0;
    if (id.x < (uint)size.x && id.y < (uint)size.y) {
        float2 p = float2(id.xy);
        float3 d;
        if ((uint(probe.w + 0.5) & 4u) != 0u) UN[id.xy] = uiEvidence(int2(id.xy));
        d.x = tanNow.x + (p.x + 0.5) / float(size.x) * (tanNow.y - tanNow.x);
        d.y = tanNow.w - (p.y + 0.5) / float(size.y) * (tanNow.w - tanNow.z);
        d.z = -1.0;
        float3 dp = float3(dot(dR0.xyz, d), dot(dR1.xyz, d), dot(dR2.xyz, d));
        float zraw = mvDepthTile[(local.y + 2) * 12 + local.x + 2];
        const float sceneZraw = zraw;
        float zPred = 0.0;   // for the mover mask: the surface's predicted depth last frame, 0 = none
        uint depthN = 0;     // ...and how many of the 3x3 have a depth now (thick or thin)
        if (knobs.y != 0.0) {
            float zr = 0.0;
            [unroll] for (int oy = -1; oy <= 1; ++oy) {
                [unroll] for (int ox = -1; ox <= 1; ++ox) {
                    float zs = mvDepthTile[(local.y + 2 + oy) * 12 + local.x + 2 + ox];
                    zr = max(zr, zs);
                    if (zs > 0.0) ++depthN;
                }
            }
            float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
            bool far = zr <= 0.0 || den <= 0.0;
            float z = far ? 0.0 : knobs.z / den;
            bool worldOn = tvCam.w != 0.0 && split.x > 0.0;
            // The scanner's interface keeps the head's path (fetchHistoryT says).
            bool scannerUi = (uint(probe.w + 0.5) & 128u) != 0u && uiCovered(region.xy + int2(p));
            if (worldOn && (far || z > split.x) && !scannerUi) {
                count15 = 1;
                dp = float3(dot(c2R0.xyz, d), dot(c2R1.xyz, d), dot(c2R2.xyz, d));
                if (!far) {
                    dp = dp * z + tvCam.xyz;
                    zPred = -dp.z;
                }
            } else if (!far) {
                dp = dp * z + tvUsed.xyz;
                zPred = -dp.z;
            } else if (split.w != 0.0 && split.z > 0.0) {
                dp = dp * split.z + tvUsed.xyz;   // the menu's assumed depth (fetchHistoryT says)
            }
            float luma = rgbToYcocg(S.Load(int3(region.xy + int2(p), 0)).rgb).x;
            if (luma > 0.6) {
                count16 = 1;
                if (zraw <= 0.0) count17 = 1;
            }
        }
        float2 motion = 0.0;
        float mover = 0.0;
        bool trackedForeground = false;
        uint decisionPath = 0u;
        bool projectionValid = false;
        bool worldAvailable = tvCam.w != 0.0 && split.x > 0.0 && knobs.y != 0.0;
        if (dp.z < -1e-6) {
            float xt = dp.x / -dp.z;
            float yt = dp.y / -dp.z;
            float2 pp;
            pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
            pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
            motion = pp - p;
            decisionPath = count15 != 0 ? 2u : 1u;
            projectionValid = true;
            float2 terrainP; float terrainZ;
            if (terrainPixel(p,d,terrainP,terrainZ)) {
                pp=terrainP; motion=pp-p; zPred=terrainZ;
                decisionPath=7u;
            }
            float2 holoP; float holoZ;
            if(holoPixel(p,0,holoP,holoZ)) {
                pp=holoP; motion=pp-p; zPred=holoZ;
                trackedForeground=true;
                decisionPath=8u;
            }
            // The mover mask, where the prediction lands on last frame's
            // image (off it NVIDIA has no history to bias against anyway).
            if (movers.x != 0.0 && pp.x >= 0.0 && pp.y >= 0.0 &&
                pp.x <= float(size.x) - 1.0 && pp.y <= float(size.y) - 1.0) {
                mover = moverAt(pp, zPred, depthN >= 6);
                if (mover != 0.0) count28 = 1;
            }
        }
        if((uint(probe.w+.5)&32u)!=0u) {
            float4 s=Screen.Load(int3(region.xy+int2(p),0));
            if(s.w>0) {
                motion=s.w!=2?s.xy+holoJitter.xy:float2(size)*2;zraw=s.z;
                trackedForeground=true;
                decisionPath=10u;projectionValid=s.w!=2;
                // The eye-space prediction above is not source-scene depth.
                // Do not apply its mover rejection to screen pixels.
                mover=0;
            }
        }
)HLSL"
R"HLSL(
        // Engine-record motion LAST (with fix.temporal_aa, probe.w 2048): a
        // pixel the game's own substituted pool draw owns takes the record's
        // exact motion over every path above; a masked one keeps no history
        // (the estimated body, ship and mesh paths retired 2026-09-23). Unbound,
        // the call returns 0 before any load and the path is byte-identical.
        bool engineMasked = false;
        float2 engineP; float engineZ;
        // Offset zero at p = id: the scene depth here is sceneZraw, held.
        const uint engineKind = enginePixelZ(p, 0, true, sceneZraw, engineP, engineZ);
#if EDVR_TEMPORAL_DIAGNOSTICS
        if (engineKind != 0u) InterlockedAdd(gCount[47u + engineKind], 1u);
#endif
        if (engineKind == 1u) {
            motion = engineP - p; zPred = engineZ;
            trackedForeground = true;
            decisionPath = 11u; projectionValid = true;
            mover = 0;
        } else if (engineKind == 2u) {
            engineMasked = true;
            mover = 0;
        }
        // Combine detected UI changes and the optional fixed UI bias.
        // World-mover rejection must not override stable marked UI.
        uint mark = probe.z != 0.0 ? uint(UM.Load(int3(id.xy,0))*255.0+0.5) : 0u;
        uint kind = mark & 3u;
        float ui = (kind == 3u || (uint(probe.w + 0.5) & 1u) != 0u) ? float(mark >> 2u)/63.0 : 0.0;
        float adaptive = adaptiveUiReactive(int2(id.xy), p + motion - holoJitter.xy);
        bool uiHere = kind == 1u || kind == 2u;
        // A masked engine pixel invalidates NVIDIA's history lookup the way a
        // hidden background does (modern presets honour only this), and sets
        // the reactive mask for the presets and FSR that read it.
        bool hidden = engineMasked || (!trackedForeground && !uiHere && backgroundHistoryHidden(local,p,motion,zraw,zPred));
        // Keep physical motion for diagnostics/reactivity. Only NVIDIA's
        // history lookup is invalidated, as with new source-screen pixels.
        float2 written = hidden ? float2(size)*2 : motion;
        MV[id.xy] = written;
        // The fovea's head lead: NVIDIA's crop history is CROP-LOCAL, so a
        // crop whose base slid by lead.xy since the frame that history came
        // from must have that slide added to every vector it reads
        // (previous = current + mv, so crop-local previous = mv + base_now -
        // base_prev). ML is a second texture, not this one: the periphery's
        // reduction, its DLAA and the UI resolve all read MV whole and must
        // see the unshifted vectors. Unbound (and lead zero) on every other
        // dispatch, where the store is dropped.
#if EDVR_TEMPORAL_TRACE
        // depthValid is a usable non-screen sample on the final route. Screen
        // z uses its source projection's private encoding, so bit 256 stays
        // clear for both valid and invalid screen paths rather than claiming
        // it is comparable with scene depth. Screen-invalid has no physical
        // correspondence, so its diagnostic xyz are zero even though MV still
        // receives the production size*2 rejection sentinel.
        bool depthValid=decisionPath!=10u && knobs.y!=0.0 && sceneZraw>knobs.x;
        float2 decisionMotion=decisionPath==10u && !projectionValid?0.0:motion;
        float decisionDepth=decisionPath==10u?0.0:zPred;
        uint decisionFlags=decisionPath | (hidden?16u:0u) |
            (decisionPath==10u && !projectionValid?32u:0u) | (uiHere?64u:0u) |
            (worldAvailable?128u:0u) | (depthValid?256u:0u) |
            (trackedForeground?512u:0u) | (projectionValid?1024u:0u);   // 2048 (static_confirmed) retired with the rigid-owner promotion
        DT[id.xy]=float4(decisionMotion,decisionDepth,float(decisionFlags));
#else
        ML[id.xy] = written + lead.xy;
#endif
)HLSL"
R"HLSL(
        MK[id.xy] = engineMasked ? 1.0 : max(adaptive, uiHere ? ui : max(ui, mover * movers.z));
        // The registration probes on the trained path (2026-09-08): main's
        // 5x5 luma SAD search, transcribed, against NVIDIA's PREVIOUS output
        // -- the history as the runtime accumulated it, bound at t1 in place
        // of the pass's own and probe.x times the render size (1 under DLAA,
        // 2 under DLSS at half), so the window steps probe.x texels to span
        // the same render pixels. Until this ran, no line in the log had
        // measured the vectors NVIDIA is handed against what it kept: the
        // probes lived in the own pass and the flown path was NVIDIA's, so a
        // station approach that "looked soft on every moving surface" had no
        // number behind it. Same classes and slots as main's, so the
        // registration line reads the same either way.
#if EDVR_TEMPORAL_DIAGNOSTICS
        if (probe.y != 0.0 && dp.z < -1e-6 && (id.x & 63) == 16 && (id.y & 63) == 16 &&
            id.x >= 8 && id.y >= 8 && id.x + 8 < (uint)size.x && id.y + 8 < (uint)size.y) {
            int2 ci = int2(id.xy);
            float curL[25];
            float meanL = 0.0;
            int kk = 0;
            [unroll] for (int wy = -2; wy <= 2; ++wy) {
                [unroll] for (int wx = -2; wx <= 2; ++wx) {
                    curL[kk] = rgbToYcocg(S.Load(int3(region.xy + ci + int2(wx, wy), 0)).rgb).x;
                    meanL += curL[kk];
                    ++kk;
                }
            }
            meanL /= 25.0;
            float varL = 0.0;
            [unroll] for (int jj = 0; jj < 25; ++jj) varL += (curL[jj] - meanL) * (curL[jj] - meanL);
            const bool sky = count15 != 0 && knobs.y != 0.0 && zraw <= 0.0;
            if (varL > (sky ? 0.0025 : 0.0225)) {
                float2 pp2 = p + motion;
                int2 pq = int2(round(pp2));
                float bestSad = 1e9;
                int2 best = int2(0, 0);
                for (int sy = -4; sy <= 4; ++sy) {
                    for (int sx = -4; sx <= 4; ++sx) {
                        float sad = 0.0;
                        int mm = 0;
                        [unroll] for (int wy2 = -2; wy2 <= 2; ++wy2) {
                            [unroll] for (int wx2 = -2; wx2 <= 2; ++wx2) {
                                int2 q = clamp(pq + int2(sx + wx2, sy + wy2), int2(0, 0), size - 1);
                                // The history at this render pixel's CENTRE, bilinear:
                                // H is probe.x times the render size, so the uv is the
                                // render pixel's own, and at 2x that is the mean of the
                                // four output texels the pixel covers. Picking one
                                // texel put every reading a quarter of a render pixel
                                // to the right and down (the first DLSS flight of the
                                // probe, 2026-09-08: +0.2 px on every class at rest).
                                float2 huv = (float2(q) + 0.5) / float2(size);
                                sad += abs(curL[mm] - rgbToYcocg(H.SampleLevel(L, huv, 0).rgb).x);
                                ++mm;
                            }
                        }
                        if (sad < bestSad) {
                            bestSad = sad;
                            best = int2(sx, sy);
                        }
                    }
                }
                float2 resid = float2(best) + (float2(pq) - pp2);
                uint base = sky ? 30u : (count15 != 0 ? 18u : 21u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base], asuint(int(round(resid.x * 100.0))));
                InterlockedAdd(Stats[base + 1], asuint(int(round(resid.y * 100.0))));
                InterlockedAdd(Stats[base + 2], 1u);
#endif
                uint base2 = sky ? 33u : (count15 != 0 ? 35u : 37u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base2], asuint(int(round(dot(resid, motion) * 100.0))));
                InterlockedAdd(Stats[base2 + 1], uint(round(dot(motion, motion) * 100.0)));
#endif
            }
        }
#endif
)HLSL"
R"HLSL(
        // The motion view on the trained path: painted into the output in
        // NVIDIA's place (the pass skips its evaluation that frame).
        if (split.y == 1.0) {
            paintDebug(id.xy, size,
                       float3(saturate(0.5 + motion.x / 16.0), saturate(0.5 + motion.y / 16.0),
                              count15 != 0 ? 1.0 : 0.0));
        } else if (split.y == 3.0) {
            float zs3 = zSceneAt(region.xy + int2(p));
            float3 o3;
            if (knobs.y == 0.0) {
                o3 = float3(0.25, 0.0, 0.25);
            } else if (zs3 > 0.0) {
                float m3 = knobs.z / (zs3 - knobs.x);
                float g3 = saturate(1.0 - log2(max(m3, 0.5)) / 8.0);
                o3 = g3.xxx;
            } else {
                o3 = float3(1.0, 0.0, 1.0);
            }
            paintDebug(id.xy, size, o3);
        } else if (split.y == 6.0) {
            // The motion-source view (with fix.temporal_aa): green where a rig
            // record's certified previous pose gave the pixel its exact motion
            // (kind 1) -- moving OR still, a still record yielding the camera
            // term through the record, so green is not a mover count; red
            // where a rig record was masked (no history), blue for a pool
            // surface that is not a rig record (the camera term), yellow for a
            // slot whose recorded depth is not the pixel's (stale: a later
            // draw changed it), magenta for a slot code arithmetic reached
            // (declined); the frame dimmed elsewhere (the camera term). On
            // foot the same colours come through the panel: the screen map's
            // validity carries 16 + the SOURCE-space kind under this view
            // (screen_motion.h), and an eye pixel showing the 2D screen is
            // painted by the kind of the source pixel it shows.
            float3 o6 = S.Load(int3(region.xy + int2(p), 0)).rgb * 0.25;
            uint k6 = engineKind;
            if (k6 == 0u && (uint(probe.w + 0.5) & 32u) != 0u) {
                const float sw6 = Screen.Load(int3(region.xy + int2(p), 0)).w;
                if (sw6 >= 16.0) k6 = uint(sw6) - 16u;
            }
            if (k6 == 1u) o6 = float3(0.0, 1.0, 0.0);
            else if (k6 == 2u) o6 = float3(1.0, 0.0, 0.0);
            else if (k6 == 3u) o6 = float3(0.0, 0.3, 1.0);
            else if (k6 == 4u) o6 = float3(1.0, 1.0, 0.0);
            else if (k6 == 5u) o6 = float3(1.0, 0.0, 1.0);
            paintDebug(id.xy, size, o6);
        }
        ZC[id.xy] = knobs.y != 0.0 ? zraw : 0.0;
    }
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (count15 != 0) InterlockedAdd(gCount[15], count15);
    if (count16 != 0) InterlockedAdd(gCount[16], count16);
    if (count17 != 0) InterlockedAdd(gCount[17], count17);
    if (count28 != 0) InterlockedAdd(gCount[28], count28);
    GroupMemoryBarrierWithGroupSync();
#endif
    // Only the counters that moved. A group whose counters are all zero --
    // which is nearly every group, since these count rare classes of pixel
    // -- used to pay forty global atomics onto forty contended addresses
    // regardless. At the Crystal Super's size that is 290,512 groups an
    // eye, so 11.6 million atomic adds an eye and 23 million a frame, for
    // a set of numbers that only a log line reads. 48..52 are engine-record
    // motion's, at Stats 50..54.
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 53 && gCount[gi] != 0) InterlockedAdd(Stats[gi < 48u ? gi : gi + 2u], gCount[gi]);
#endif
}
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
[numthreads(8, 8, 1)]
void main(uint3 id : SV_DispatchThreadID, uint gi : SV_GroupIndex) {
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 48) gCount[gi] = 0;
    GroupMemoryBarrierWithGroupSync();
#endif
    uint count[48] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    // The fovea's compose overwrites this rectangle every pixel at weight 1
    // (temporal_pass.cpp only ever sets skip when it has verified that), so
    // an in-skip pixel skips the colour resolve below and takes the short
    // branch after it instead, which still makes the three writes the next
    // frame reads back. Neither branch ever `return`s, so every thread in
    // the group reaches the SAME barriers at the tail -- a return here would
    // make that divergent within a group. skip.zw both zero (the default)
    // means no skip, so this never fires when the fovea is off.
    const bool inSkip = skip.z > skip.x && skip.w > skip.y &&
                        id.x >= (uint)skip.x && id.x < (uint)skip.z &&
                        id.y >= (uint)skip.y && id.y < (uint)skip.w;
    if (id.x < (uint)size.x && id.y < (uint)size.y && !inSkip) {
        float2 p = float2(id.xy);
        int2 ci = int2(id.xy);
        if ((uint(probe.w + 0.5) & 4u) != 0u) UN[id.xy] = uiEvidence(ci);
        // Foveation-aware periphery (docs/performance.md feature 6, the
        // sharp periphery only): toward the frame's edge the history's
        // WEIGHT is eased down and the fallback sample is blurred a little
        // more. A lighter history cuts the motion smear (a heavier one
        // smears -- the 2026-09-05 field lesson); the wider Gaussian holds
        // the flicker down spatially without the lag a heavier history
        // adds. Mild, because with a fixed centre the player looks straight
        // at the periphery whenever the eyes move; the ramp starts at the
        // fovea's edge (outside the blend band) and reaches full strength at
        // the farthest frame corner. ecc is exactly 0 when the fovea is off
        // (fovea1.w == 0), so the full-frame pass is unchanged (blend >= 0.5
        // never reaches the 0.40 floor at ecc 0).
        float ecc = 0.0;
        if (fovea1.w != 0.0) {
            float dist = length(p - fovea0.xy);
            ecc = saturate((dist - fovea0.z) * fovea0.w) * fovea1.x;
        }
        float blEff = blend - ecc * 0.30;                // history: LIGHTER toward the edge
        if (blEff < 0.40) blEff = 0.40;
        float gEff = gamma;                              // clamp unchanged
        float curK = 2.29 / (1.0 + ecc * 1.5);           // the fallback Gaussian widens (spatial low-pass), mildly
        // This frame's sample and its neighbourhood, in one pass over the
        // 3x3 around the pixel. The sample the game rendered at q sits at
        // q - jit on the unjittered grid, so each is weighted by its
        // distance from THIS pixel's centre there: exp(-2.29 d^2), a
        // Gaussian of sigma 0.47 px, UE4's filter for the same job. Two
        // The blend uses the filtered value, so a pixel whose history is
        // rejected shows a spatially settled sample rather than the raw
        // one hopping by the jitter. The neighbourhood's moments are NOT
        // weighted the same way: the sixth build tried that, the box
        // narrowed to the filter's width, the clip fired on a third of
        // the pixels at rest by hair-widths, and the picture shimmered
        // faintly everywhere (measured 2026-09-03: 35% clipped by 0.3/255
        // with the head still, against 11% by 0.5 before). The plain 3x3
        // it is. At 3096 wide before a 1.5x resolve the filter's
        // softening is a third of an output pixel; the sharpen recovers
        // the rest. advanced.temporal_aa_current = raw gives the point
        // sample back for an A/B.
        float4 cur = 0.0;
        float wsum = 0.0;
        float3 m1 = 0.0;
        float3 m2 = 0.0;
        float msum = 0.0;
        [unroll] for (int dy = -1; dy <= 1; ++dy) {
            [unroll] for (int dx = -1; dx <= 1; ++dx) {
                int2 q = clamp(ci + int2(dx, dy), int2(0, 0), size - 1);
                float4 sq = S.Load(int3(region.xy + q, 0));
                float2 dpos = float2(dx, dy) - jit.xy;
                float w = jit.z != 0.0 ? exp(-curK * dot(dpos, dpos))
                                       : ((dx == 0 && dy == 0) ? 1.0 : 0.0);
                float wm = 1.0;
                cur += sq * w;
                wsum += w;
                float3 s = rgbToYcocg(sq.rgb);
                m1 += s * wm;
                m2 += s * s * wm;
                msum += wm;
            }
        }
        cur /= max(wsum, 1e-6);
        // The bright pixels, and the bright pixels with no depth behind
        // them: HUD text the game draws without a depth write takes the
        // rotation-only path and cannot register under head translation
        // (the review of 2026-09-04, H5, believed; this counts it).
        {
            float lumaC = rgbToYcocg(S.Load(int3(region.xy + ci, 0)).rgb).x;
            if (lumaC > 0.6) {
                count[16] = 1;
                if (knobs.y != 0.0 && zAt(region.xy + ci) <= 0.0) count[17] = 1;
            }
        }
        m1 /= msum;
        m2 /= msum;
        float3 sigma = sqrt(max(m2 - m1 * m1, 0.0));
        float3 boxMin = m1 - gEff * sigma;
        float3 boxMax = m1 + gEff * sigma;
        float3 outc = cur.rgb;
        bool used = false;
        uint worldTaken = 0;
        float2 mvUsed = 0.0;
        float errUsed = 0.0;
        float mover = 0.0;
        if (haveHistory != 0) {
            float3 hy;
            float zPred = 0.0;
            uint depthN = 0;
            if (fetchHistoryT(p, dR0.xyz, dR1.xyz, dR2.xyz, tvUsed.xyz,
                              knobs.y != 0.0 && tvUsed.w != 0.0, true, worldTaken, mvUsed, zPred,
                              depthN, hy)) {
                if (worldTaken != 0) count[15] = 1;
                // The mover mask (moverAt says): a masked pixel keeps less
                // of its history, by the strength -- at 1 it is the fresh
)HLSL"
R"HLSL(
                // frame alone, spatially settled by the filter above.
                uint uiKind = probe.z != 0.0 ? uint(UM.Load(int3(ci,0))*255.0+0.5)&3u : 0u;
                if (movers.x != 0.0 && uiKind != 1u && uiKind != 2u) {
                    mover = moverAt(p + mvUsed, zPred, depthN >= 6);
                    if (mover != 0.0) {
                        count[28] = 1;
                        blEff *= 1.0 - movers.z;
                    }
                }
                errUsed = saturate(abs(hy.x - rgbToYcocg(cur.rgb).x) * 4.0);
                blEff *= 1.0 - adaptiveUiReactive(int2(round(p+jit.xy)), p + mvUsed + jit.xy - holoJitter.xy);
                float3 hc = clipToBox(boxMin, boxMax, hy);
                if (any(abs(hc - hy) > 1e-4)) {
                    count[1] = 1;
                    count[2] = clipSize(hc, hy);
                }
                // The used delta's clip share per class: the world path's
                // pixels and the ship's, since the two are registered by
                // different deltas and one number hid the other.
                if (worldTaken != 0) {
                    count[24] = 1;
                    if (count[1] != 0) count[25] = 1;
                } else {
                    count[26] = 1;
                    if (count[1] != 0) count[27] = 1;
                }
                outc = lerp(cur.rgb, ycocgToRgb(hc), blEff);
                used = true;
            }
#if EDVR_TEMPORAL_DIAGNOSTICS
            // The registration instrument: what each candidate would have
            // fetched, judged by the same clip, counted and not used. The
            // candidates: 0 the head's rotation alone, 2 the world path's
            // delta from the game's view rows, 3 the head with depth as
            // used, 1 the same with the other eye's translation. Up to four
            // pixel while it runs.
            [unroll] for (int c = 0; c < 4; ++c) {
                if ((candMask & (1 << c)) == 0) continue;
                float3 r0 = c == 0 ? c0R0.xyz : (c == 1 ? c1R0.xyz : (c == 2 ? c2R0.xyz : c3R0.xyz));
                float3 r1 = c == 0 ? c0R1.xyz : (c == 1 ? c1R1.xyz : (c == 2 ? c2R1.xyz : c3R1.xyz));
                float3 r2 = c == 0 ? c0R2.xyz : (c == 1 ? c1R2.xyz : (c == 2 ? c2R2.xyz : c3R2.xyz));
                // Candidate 2 is the world path's delta from the game's view
                // rows, judged rotation-only; 3 is the head with depth as
                // used for the ship's own pixels; 1 is 3 again with the
                // OTHER eye's translation, which is the whole test of
                // whether the depth textures are assigned to the right
                // eyes -- so it must reproject with depth exactly as 3
                // does, or it collapses into a copy of candidate 0 and
                // measures nothing.
                float3 tvc = c == 1 ? tvCand.xyz : tvUsed.xyz;
                bool depthC = knobs.y != 0.0 && (c == 3 || c == 1);
                float3 h;
                uint wc = 0;
                float2 mvc = 0.0;
                float zc = 0.0;
                uint dnc = 0;
                if (!fetchHistoryT(p, r0, r1, r2, tvc, depthC, false, wc, mvc, zc, dnc, h)) {
                    count[3 + c * 3] = 1;
                } else {
                    float3 hc2 = clipToBox(boxMin, boxMax, h);
                    if (any(abs(hc2 - h) > 1e-4)) {
                        count[4 + c * 3] = 1;
                        count[5 + c * 3] = clipSize(hc2, h);
                    }
                }
            }
#endif
        }
#if EDVR_TEMPORAL_DIAGNOSTICS
        // The registration probes: on a 64-pixel grid, where the frame has
        // texture, the history's best match within 4 px of the predicted
        // position by a 5x5 luma SAD. The mean offset per class -- the
        // world path, the ship -- is the used reprojection's systematic
        // error in pixels, which no clip share can give: a steady offset
        // that follows the motion is a lag or a scale, noise averages to
        // zero, and the jitter's sub-pixel offset is in every probe and
        // averages out too. Signed: (+2, 0) means the content sat two
        // pixels further right in the history than the prediction said.
        if (used && (id.x & 63) == 16 && (id.y & 63) == 16 && id.x >= 8 && id.y >= 8 &&
            id.x + 8 < (uint)size.x && id.y + 8 < (uint)size.y) {
            float curL[25];
            float meanL = 0.0;
            int kk = 0;
            [unroll] for (int wy = -2; wy <= 2; ++wy) {
                [unroll] for (int wx = -2; wx <= 2; ++wx) {
                    curL[kk] = rgbToYcocg(S.Load(int3(region.xy + ci + int2(wx, wy), 0)).rgb).x;
                    meanL += curL[kk];
                    ++kk;
                }
            }
            meanL /= 25.0;
            float varL = 0.0;
            [unroll] for (int jj = 0; jj < 25; ++jj) varL += (curL[jj] - meanL) * (curL[jj] - meanL);
            // Three classes: the sky (the far plane, whose Milky Way is soft,
            // so its texture bar is lower), the world with a depth (a station,
            // whose own rotation is in no vector and shows here), the ship.
            const bool sky = worldTaken != 0 && knobs.y != 0.0 && zAt(region.xy + ci) <= 0.0;
            if (varL > (sky ? 0.0025 : 0.0225)) {
                float2 pp = p + mvUsed;
                int2 pq = int2(round(pp));
                float bestSad = 1e9;
                int2 best = int2(0, 0);
                for (int sy = -4; sy <= 4; ++sy) {
                    for (int sx = -4; sx <= 4; ++sx) {
                        float sad = 0.0;
                        int mm = 0;
                        [unroll] for (int wy2 = -2; wy2 <= 2; ++wy2) {
                            [unroll] for (int wx2 = -2; wx2 <= 2; ++wx2) {
                                int2 q = clamp(pq + int2(sx + wx2, sy + wy2), int2(0, 0), size - 1);
                                sad += abs(curL[mm] - rgbToYcocg(H.Load(int3(q, 0)).rgb).x);
                                ++mm;
                            }
                        }
                        if (sad < bestSad) {
                            bestSad = sad;
                            best = int2(sx, sy);
                        }
                    }
                }
                float2 resid = float2(best) + (float2(pq) - pp);
                uint base = sky ? 30u : (worldTaken != 0 ? 18u : 21u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base], asuint(int(round(resid.x * 100.0))));
                InterlockedAdd(Stats[base + 1], asuint(int(round(resid.y * 100.0))));
                InterlockedAdd(Stats[base + 2], 1u);
#endif
                // The match against the prediction's own motion, for a
                // least-squares scale: with resid = k * mv the true motion
                // was (1 + k) times the vector, k = sum(resid.mv) /
                // sum(mv.mv) over the class. A signed mean cancels over a
                // head that turns both ways; this does not.
                uint base2 = sky ? 33u : (worldTaken != 0 ? 35u : 37u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base2], asuint(int(round(dot(resid, mvUsed) * 100.0))));
                InterlockedAdd(Stats[base2 + 1], uint(round(dot(mvUsed, mvUsed) * 100.0)));
#endif
            }
        }
#endif
        if (!used) count[0] = 1;
        float3 o = saturate(outc);
        N[id.xy] = float4(o, 1.0);
        // This frame's depth, kept for next frame's mover mask (movers.w):
        // the trained path's mv entry writes the same copy for NVIDIA.
        if (movers.w != 0.0) ZC[id.xy] = zAt(region.xy + ci);
        // The debug views (advanced.temporal_aa_debug): the history keeps
        // accumulating as normal, only what leaves changes. motion paints
        // the used reprojection -- +x red, +y green, around mid-grey with
        // 16 px to the rail -- and the world path in blue; error paints
        // how far the fetched history sat from this frame's sample, in
        // luma, four times over. A skybox that leads or trails its true
        // motion shows as a colour that disagrees with the ship's turn.
        if (split.y == 1.0) {
            o = float3(saturate(0.5 + mvUsed.x / 16.0), saturate(0.5 + mvUsed.y / 16.0),
                       worldTaken != 0 ? 1.0 : 0.0);
        } else if (split.y == 2.0) {
            o = errUsed.xxx;
        } else if (split.y == 3.0) {
            // The depth view: where each pixel's depth comes from -- the
            // scene's in grey by distance (near bright, log scale to
            // 256 m), none in magenta, no depth bound at all in dark
            // purple. HUD text shows magenta: it has no depth of its own
            // and reprojects by what is behind it.
            float zs3 = zSceneAt(region.xy + ci);
            if (knobs.y == 0.0) {
                o = float3(0.25, 0.0, 0.25);
            } else if (zs3 > 0.0) {
                float m3 = knobs.z / (zs3 - knobs.x);
                float g3 = saturate(1.0 - log2(max(m3, 0.5)) / 8.0);
                o = g3.xxx;
            } else {
                o = float3(1.0, 0.0, 1.0);
            }
        } else if (split.y == 6.0) {
            // The motion-source view, as the mv entry paints it (the panel's
            // source-space kind included).
            float2 eP6; float eZ6;
            uint ek6 = enginePixel(float2(ci), jit.xy, eP6, eZ6);
            if (ek6 == 0u && (uint(probe.w + 0.5) & 32u) != 0u) {
                const float sw6 = Screen.Load(int3(region.xy + ci, 0)).w;
                if (sw6 >= 16.0) ek6 = uint(sw6) - 16u;
            }
            o = ek6 == 1u ? float3(0.0, 1.0, 0.0) : ek6 == 2u ? float3(1.0, 0.0, 0.0)
              : ek6 == 3u ? float3(0.0, 0.3, 1.0) : ek6 == 4u ? float3(1.0, 1.0, 0.0)
              : ek6 == 5u ? float3(1.0, 0.0, 1.0) : cur.rgb * 0.25;
        }
        O[id.xy] = float4(o, cur.a);
    }
    // The skipped interior: only the colour RESOLVE above is skipped there,
    // never the three writes the NEXT frame reads back. The UI evidence
    // (UN/u6) and the mover mask's depth carry (ZC/u4) are written under the
    // same two tests as above, and the colour history is refreshed from the
    // RAW current frame -- the resolve's own centre tap, stored the way the
    // resolve stores a pure pass-through (saturate of the RGB it loaded), so
    // it is the history's own encoding and nothing here can go stale. No O
    // write: the compose overwrites this rectangle at weight 1, so it never
    // reads the periphery inside it, and the composite is what is submitted
    // whenever temporal_pass.cpp arms the skip. Sibling of the block above,
    // not nested in it, and barrier-free: every thread in the group still
    // reaches the SAME tail barriers whichever branch it took.
    if (inSkip && id.x < (uint)size.x && id.y < (uint)size.y) {
        int2 ci = int2(id.xy);
        if ((uint(probe.w + 0.5) & 4u) != 0u) UN[id.xy] = uiEvidence(ci);
        float4 cur = S.Load(int3(region.xy + ci, 0));
        N[id.xy] = float4(saturate(cur.rgb), 1.0);
        if (movers.w != 0.0) ZC[id.xy] = zAt(region.xy + ci);
    }
    // One atomic per group per counter, not per pixel -- and none at all
    // for a counter that did not move, which is most of them in most
    // groups.
    [unroll] for (int k = 0; k < 48; ++k) {
#if EDVR_TEMPORAL_DIAGNOSTICS
        if (count[k] != 0) InterlockedAdd(gCount[k], count[k]);
#endif
    }
#if EDVR_TEMPORAL_DIAGNOSTICS
    GroupMemoryBarrierWithGroupSync();
    if (gi < 48 && gCount[gi] != 0) InterlockedAdd(Stats[gi], gCount[gi]);
#endif
}
)HLSL";

}  // namespace edvr
